### ISSUE TITLE
The provided API key is invalid.

### ISSUE THREAD

**Issue by rahulpv** [tolu360/react-native-google-places#200]
Getting this response after adding the beta plugin to the project. The same key is working in web url(After changing application restriction to none).

added RNGP_ANDRIOD_API_KEY=***** in gradle.properties

**Comment by tolu360** [comment]
This is NOT an issue at all - that error is from Google and it is self-explanatory. 

- Go back to the Google Cloud Console, follow the steps here - [https://developers.google.com/places/android-sdk/signup](https://developers.google.com/places/android-sdk/signup)
- Create a different key for all your Android apps and a separate key for your iOS apps.
- Set key restrictions to `application restrictions` for each key.
- For the Android key, add the package name and fingerprints of each app that would use the key
- Enable or add permissions for Google Places, Google Maps SDK for Android and Google Maps SDK for iOS.
- **Enable billing for your account** and only use keys from Projects tied to that billing account.

Recompile your app and test again. Cheers!

**Comment by rahulpv** [comment]
Yeah, I did.. Bu getting same error again. 

SHA-1 fingerprint is from "RELEASE CERTIFICATE".

so do we need to update "signingConfigs"? I have only updated "defaultConfig" with "multiDexEnabled true"

**Comment by tolu360** [comment]
Are you also testing a release build? Else add your debug fingerprint when in running a debug build.

**Comment by rahulpv** [comment]
Yes.. still getting the same error...  any suggestions to test or debug?

**Comment by rahulpv** [comment]
{"framesToPop":1,"nativeStackAndroid":[{"methodName":"onActivityResult","lineNumber":112,"file":"RNGooglePlacesModule.java"},{"methodName":"onActivityResult","lineNumber":253,"file":"ReactContext.java"},{"methodName":"onActivityResult","lineNumber":703,"file":"ReactInstanceManager.java"},{"methodName":"onActivityResult","lineNumber":129,"file":"ReactActivityDelegate.java"},{"methodName":"onActivityResult","lineNumber":75,"file":"ReactActivity.java"},{"methodName":"dispatchActivityResult","lineNumber":7454,"file":"Activity.java"},{"methodName":"deliverResults","lineNumber":4353,"file":"ActivityThread.java"},{"methodName":"handleSendResult","lineNumber":4402,"file":"ActivityThread.java"},{"methodName":"execute","lineNumber":49,"file":"ActivityResultItem.java"},{"methodName":"executeCallbacks","lineNumber":108,"file":"TransactionExecutor.java"}],"userInfo":null,"code":"E_RESULT_ERROR"}


this is console "error" response

**Comment by tolu360** [comment]
You just need to fix your API key - that's all. Is billing enabled for this account? In addition to your release fingerprint, do you also have your debug fingerprint on the cloud console? Please quote the question you are responding to so I know which of my questions your answer(s) is/are for.

Also try to add your key to a system environment by running 
```bash
export RNGP_ANDRIOD_API_KEY=Insert_API_KEY_here
```
if you are on a Mac and try to build again.

**Comment by rahulpv** [comment]
It worked after running
`export RNGP_ANDRIOD_API_KEY=Insert_API_KEY_here`

**Comment by rahulpv** [comment]
Please see my gradle properties 

<img width="259" alt="Screenshot 2019-03-13 at 2 31 03 AM" src="https://user-images.githubusercontent.com/4536770/54235797-14be1f00-4538-11e9-8fe6-970719365cb9.png">

**Comment by tolu360** [comment]
Interesting! I could use that feedback and take a look at the gradle settings for the lib again. Glad it is now working for you. 

The way I have set things to work is to first check for a system variable for the key before looking in `gradle.properties`. Your file looks good to me though.

Do some testing for me, will you? Intentionally remove the system variable by running

```bash
export RNGP_ANDRIOD_API_KEY=
```
Leave the correct key in `gradle.properties` and build your app again. Check if it is still working and let me know, thanks.

**Comment by rahulpv** [comment]
Yes It worked after running 
`
export RNGP_ANDRIOD_API_KEY=
`
But when I unset "RNGP_ANDRIOD_API_KEY" I'm getting same error

**Comment by rahulpv** [comment]
Guess You have to update this condition

`       
 resValue "string", "places_api_key", ("$System.env.RNGP_ANDRIOD_API_KEY" ?: (rootProject.findProperty("RNGP_ANDRIOD_API_KEY") ?: ""))
`

**Comment by tolu360** [comment]
Yeah, that was what I was hoping to see from your test. Would push another beta update. Thanks for testing!

**Comment by tolu360** [comment]
So I just tagged 3.0.0-beta.11, pull in the update and let me know if it fixes this issue for you - test to see that either setting the key in `gradle.properties` or setting it in system env works just fine. Also note that I corrected the typo in `RNGP_ANDROID_API_KEY`

**Comment by codal-mpawar** [comment]
hey dear,

PLACES_API_ACCESS_NOT_CONFIGURED error status is not solved help me

**Comment by novenix** [comment]
i really dont undertand the process, because in the google api key, i put my key that generate running  keytool -list -v -keystore debug.keystore in c/users/user/andorid.
after that y put my key in gradle.propierties, after that, i put my api key in build. gradle of the react-native-google-places module in the space of INSERT_KEY_HERE.
i know im missing something(i have the places api enabled with billing)
im very new with all the google cloud services(like 2 weeks ago) i dont know how really set the api for google places in react-native :(.
i hope you can help me

**Comment by novenix** [comment]
is a little difficult because i'm so new, i really learn to use redux and react native like 2 months ago , and for example, setting this kind of configurations is so difficult. i dont know how to set it how it's supposed to be, you can help me with an example or a step guide? :(

**Comment by congnguyen91** [comment]
How can I read the API key from .env file :) like .env.dev, .env.release
Only one gradle.properties file but the project may have many keys for debug, release.

**Comment by codal-mpawar** [comment]
@congnguyen91  there is no need to .env file 

just copy key and paste at gradle.properties 
also you need to add meta tag in androidmanifest file 
<meta-data
        android:name="com.google.android.maps.v2.API_KEY"
        android:value="88888888888888888888888888888" />

**Comment by codal-mpawar** [comment]
@novenix  please refer the beta version react-native-google-places

**Comment by tolu360** [comment]
> How can I read the API key from .env file :) like .env.dev, .env.release
> Only one gradle.properties file but the project may have many keys for debug, release.

Either swap out the keys in `gradle.properties` for each type of build or use `System Variables` as described in the [docs](https://github.com/tolu360/react-native-google-places/blob/master/BETA_README.md#android-api-key). Or if you want to continue working with `gradle.properties`, you can check out [react-native-config](https://github.com/luggit/react-native-config) which can allow you work with `.env` files natively. Also ensure you are on the latest beta release before making these changes, these are not supported on versions before v3.

**Comment by tolu360** [comment]
> @congnguyen91 there is no need to .env file
> 
> just copy key and paste at gradle.properties
> also you need to add meta tag in androidmanifest file

Note that meta tag in your manifest file is not required in the latest beta (v3)

**Comment by tolu360** [comment]
This issue is resolved, if you have other issues aside this, open a new issue for that. Cheers everyone!

**Comment by congnguyen91** [comment]
I found a solution
![Screen Shot 2019-03-20 at 6 23 00 PM](https://user-images.githubusercontent.com/18322684/54680735-3b361880-4b3d-11e9-9615-ef636a8f5fb2.png)

=> use env

**Comment by congnguyen91** [comment]
@tolu360 thanks you sometime we need separate keys :) cause of two app packages (debug/release)

**Comment by tolu360** [comment]
> I found a solution
> ![Screen Shot 2019-03-20 at 6 23 00 PM](https://user-images.githubusercontent.com/18322684/54680735-3b361880-4b3d-11e9-9615-ef636a8f5fb2.png)
> 
> => Note: Override resources string - add for all buildTypes: debug/release/staging

This is a way to solve this but one that may break with future updates. Why don't you consider using your env variable in gradle.properties instead:

```groovy
RNGP_ANDROID_API_KEY=project.env.get("API_KEY_HERE")
```

**Comment by kenvunz** [comment]
Thanks @congnguyen91, your solution works well when using `react-native-config` to define ENV variables

@tolu360 tried running `project.env.get()` in `gradle.properties` but it doesn't get executed

**Comment by igorlamos** [comment]
> This is a way to solve this but **one that may break with future updates**. Why don't you consider using your env variable in gradle.properties instead:
> 
> ```groovy
> RNGP_ANDROID_API_KEY=project.env.get("API_KEY_HERE")
> ```

@tolu360 Overriding [`places_api_key`](https://github.com/tolu360/react-native-google-places/blob/master/android/src/main/java/com/arttitude360/reactnative/rngoogleplaces/RNGooglePlacesModule.java#L79) using 
```
resValue "string", "places_api_key", project.env.get("GOOGLE_API_KEY_ANDROID")
```
in app's `android/build.gradle` file may break with future updates as well as using [`RNGP_ANDROID_API_KEY`](https://github.com/tolu360/react-native-google-places/blob/master/android/build.gradle#L19).

As `react-native-config`'s `project.env.get()` is not working inside `gradle.properties`, overriding `places_api_key` is the only working solution for us who are using `.env`(s) and don't want to copy/paste values before each and every build or have these values stored differently on local and/or CI/CD.

Thanks @congnguyen91 for finding a solution :-) You may also place it in `defaultConfig` as the `.env` variable name is always the same and the API key differs based on `.env` file loaded.

@tolu360 If we agree on a better way on how to solve this, I'll be more than happy to prepare the PR. I assume, that most of us using this library are also using react-native-maps, which stores `API_KEY` in `com.google.android.geo.API_KEY` metadata name, which is "the recommended metadata name for the API key" (according Google). What do you think?

**Comment by nateeither** [comment]
Reopen this issue. I had similiar error on android. Working well on ios

**Comment by nateeither** [comment]
I have same issue on android. I'm using rngp v.3.1.2 
I put my key on gradle.properties and it doesn't work at all.
